######
include:
  template: Jobs/Secret-Detection.latest.gitlab-ci.yml
######
image: alpine
pages:
  stage: deploy
  script:
  - echo 'Nothing to do...'
  artifacts:
    paths:
    - public
  only:
  - main
