name: Caching Assets

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache Assets
      id: cache-assets
      uses: actions/cache@v3
      with:
        path: public
        key: ${{ runner.os }}-assets

    - name: antinazi-cache.js
